require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ids", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Id. As you add validations to Id, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Id.create! valid_attributes
      get ids_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      id = Id.create! valid_attributes
      get id_url(id)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_id_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      id = Id.create! valid_attributes
      get edit_id_url(id)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Id" do
        expect {
          post ids_url, params: { id: valid_attributes }
        }.to change(Id, :count).by(1)
      end

      it "redirects to the created id" do
        post ids_url, params: { id: valid_attributes }
        expect(response).to redirect_to(id_url(Id.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Id" do
        expect {
          post ids_url, params: { id: invalid_attributes }
        }.to change(Id, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ids_url, params: { id: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested id" do
        id = Id.create! valid_attributes
        patch id_url(id), params: { id: new_attributes }
        id.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the id" do
        id = Id.create! valid_attributes
        patch id_url(id), params: { id: new_attributes }
        id.reload
        expect(response).to redirect_to(id_url(id))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        id = Id.create! valid_attributes
        patch id_url(id), params: { id: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested id" do
      id = Id.create! valid_attributes
      expect {
        delete id_url(id)
      }.to change(Id, :count).by(-1)
    end

    it "redirects to the ids list" do
      id = Id.create! valid_attributes
      delete id_url(id)
      expect(response).to redirect_to(ids_url)
    end
  end
end
